version: '3.1'
services:
  ricky-mysql:
    image: 'mysql:8.0'
    container_name: ricky-mysql
    working_dir: /var/www/myapp
    volumes:
        - ./mysql/docker-data:/var/lib/mysql
        - ./mysql/docker-data-files:/var/lib/mysql-files
        - ./cake:/var/www/myapp
        - ./mysql/my.cnf:/etc/mysql/my.cnf
        - ./mysql/:/etc/mysql/myhost-mysql/
    ports:
      - "8106:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  ricky-nginx:
    image: 'nginx:alpine'
    container_name: ricky-nginx
    working_dir: /var/www/myapp
    volumes:
        - ./cake:/var/www/myapp
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
     - "8180:80"
  ricky-cake:
    build: ./cake
    container_name: ricky-cake
    working_dir: /var/www/myapp
    environment:
      - DG_HOST=${DG_HOST}
      - DG_USERNAME=${DG_USERNAME}
      - DG_KEY=${DG_KEY}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@ricky-mysql:3306/${MYSQL_DATABASE}?encoding=utf8&timezone=UTC&cacheMetadata=true&quoteIdentifiers=false&persistent=false
    volumes:
      - ./cake:/var/www/myapp
      - ./cake/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
